import test from 'node:test';import assert from 'node:assert/strict';
import {hasIdentifiers,officialURL,frequency,actionLevel,verifiedEffects,POST} from '../api/medivue.js';
const raw='TestDrug 10 mg tablets. Possible side effects. Common: headache. Rare: rash. Contact a doctor immediately for rash.';
const request=b=>new Request('https://www.vueapps.se/api/medivue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language:'en',privacyConfirmed:true,action:'review',identityConfirmed:true,name:'TestDrug',strength:'10 mg',form:'tablets',country:'Sweden',leaflet:raw,...b})});
async function mock(run){const old=globalThis.fetch,keys=['OPENAI_API_KEY','KV_REST_API_URL','KV_REST_API_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN'],before=Object.fromEntries(keys.map(k=>[k,process.env[k]]));process.env.OPENAI_API_KEY='test';process.env.KV_REST_API_URL='https://redis.example';process.env.KV_REST_API_TOKEN='test';delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.UPSTASH_REDIS_REST_TOKEN;try{await run()}finally{globalThis.fetch=old;for(const k of keys)if(before[k]===undefined)delete process.env[k];else process.env[k]=before[k]}}
const result=report=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(report)}]}]});
test('identifiers and unconfirmed identity/privacy rejected before provider/budget calls',async()=>{await mock(async()=>{let calls=0;globalThis.fetch=async()=>{calls++;throw Error('unexpected')};for(const body of [{privacyConfirmed:false},{identityConfirmed:false},{leaflet:'TestDrug 19651112-1234'},{leaflet:'patient: Jane'},{leaflet:'Contact jane@example.com'}])assert.equal((await POST(request(body))).status,400);assert.equal(calls,0)});assert.ok(hasIdentifiers('6511121234'));assert.ok(!hasIdentifiers('TestDrug 10 mg tablets'))});
test('official source host validation rejects impersonators, redirects to private hosts and credentials',()=>{assert.ok(officialURL('https://www.fass.se/'));for(const url of ['https://fass.se.evil.example','http://fass.se/','https://user@fass.se/','https://127.0.0.1/','https://fass.se:8443'])assert.equal(officialURL(url),null)});
test('frequency is independent of urgency, and conflicting group headings stay unknown',()=>{assert.equal(frequency('Mycket sällsynta'),'very_rare');assert.equal(frequency('Mindre vanliga'),'uncommon');assert.equal(frequency('Very common headache. Rare rash.'),'unknown');assert.equal(actionLevel('Contact a doctor immediately'),'urgent');assert.equal(actionLevel('Do not contact a doctor'),'unspecified');assert.equal(actionLevel('Nausea'),'unspecified')});
test('hallucinated or stitched leaflet excerpts and mixed group frequency cannot become classifications',()=>{const effects=verifiedEffects([{effect:'headache',excerpt:'Common: headache.',frequencyQuote:'Common',actionQuote:'immediately'},{effect:'rash',excerpt:'Common: headache. Rare: rash.',frequencyQuote:'Common'},{effect:'blindness',excerpt:'Common: blindness.',frequencyQuote:'Common'}],raw);assert.equal(effects.length,2);assert.equal(effects[0].frequency,'common');assert.equal(effects[0].action,'unspecified');assert.equal(effects[1].frequency,'unknown')});
test('matching uploaded text is explicitly unverified and never supplies a personal risk score',async()=>{await mock(async()=>{globalThis.fetch=async(url,o)=>{if(url==='https://redis.example')return Response.json({result:1});const b=JSON.parse(o.body);assert.equal(b.store,false);assert.match(b.instructions,/Never recommend starting, stopping/);assert.ok(!b.tools);return result({personalData:false,matched:true,country:'Sweden',identityQuote:'TestDrug 10 mg tablets.',effects:[{effect:'headache',excerpt:'Common: headache.',frequencyQuote:'Common'}]})};const r=await POST(request({}));assert.equal(r.status,200);const d=await r.json();assert.equal(d.matched,true);assert.equal(d.source.type,'user_supplied_unverified');assert.equal(d.effects[0].frequency,'common');assert.equal(d.incomplete,true);assert.equal(d.noPersonalRiskScore,true)})});
test('wrong strength, country or model privacy flag cannot produce a medical report',async()=>{await mock(async()=>{let report={personalData:false,matched:true,country:'Sweden',identityQuote:'TestDrug 20 mg tablets.',effects:[{effect:'headache',excerpt:'Common: headache.',frequencyQuote:'Common'}]};globalThis.fetch=async url=>url==='https://redis.example'?Response.json({result:1}):result(report);assert.equal((await (await POST(request({}))).json()).matched,false);report={...report,country:'US',identityQuote:'TestDrug 10 mg tablets.'};assert.equal((await (await POST(request({}))).json()).matched,false);report.personalData=true;assert.equal((await POST(request({}))).status,400)})});
test('exhausted shared budget fails closed without sending medical inputs to AI',async()=>{await mock(async()=>{let provider=0;globalThis.fetch=async url=>{if(url==='https://redis.example')return Response.json({result:1000});provider++;throw Error('unexpected')};assert.equal((await POST(request({}))).status,429);assert.equal(provider,0)})});
test('official review shows passages only after server retrieval and exact product matching',async()=>{await mock(async()=>{const url='https://www.fass.se/medicines/test';globalThis.fetch=async(u,o)=>{if(u==='https://redis.example')return Response.json({result:1});if(u===url)return new Response('<html><p>'+raw+'</p></html>',{headers:{'Content-Type':'text/html'}});const b=JSON.parse(o.body);assert.equal(b.tool_choice,'required');assert.ok(b.tools[0].filters.allowed_domains.includes('fass.se'));return Response.json({status:'completed',output:[{type:'web_search_call',status:'completed',action:{sources:[{url}]}},{type:'message',content:[{type:'output_text',text:JSON.stringify({personalData:false,matched:true,country:'Sweden',url,identityQuote:'TestDrug 10 mg tablets.',effects:[{effect:'rash',excerpt:'Rare: rash. Contact a doctor immediately for rash.',frequencyQuote:'Rare',actionQuote:'Contact a doctor immediately for rash.'}]})}]}]})};const d=await (await POST(request({leaflet:''}))).json();assert.equal(d.source.type,'official_page_passages_verified');assert.equal(d.effects[0].frequency,'rare');assert.equal(d.effects[0].action,'urgent')})});
