import test from 'node:test';
import assert from 'node:assert/strict';
import {VueMemory,sanitizeFields,selectHistory} from './memory.js';
import {memoryContext} from './memory-context.js';
import {publicRecord,publicURL,collectPublicEvidence,readPublicEvidence} from './specialist-memory.js';
import {POST,urgentFollowup} from '../api/vue-followup.js';
import {GET} from '../api/vue-memory.js';
function storage(){const db=new Map();return {getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v),removeItem:k=>db.delete(k)}}
test('case reload and switch preserve relevant object history without merging cases or domains',()=>{const s=storage(),m=new VueMemory({domain:'antiqvue',storage:s});const a=m.create('Chair',{description:'Oak chair'});m.append({question:'What about the oak legs?',answer:'Check joinery'});const b=m.create('Ring',{description:'Gold ring'});m.append({question:'What mark?',answer:'Photograph hallmark'});const reload=new VueMemory({domain:'antiqvue',storage:s});assert.equal(reload.active().id,b.id);reload.switch(a.id);assert.equal(reload.history('legs')[0].answer,'Check joinery');assert.equal(reload.active().fields.description,'Oak chair');assert.equal(new VueMemory({domain:'vinylvue',storage:s}).db.cases.length,0)});
test('medical session memory never persists and rejects obvious identifiers or media',()=>{const s=storage(),m=new VueMemory({domain:'medivue',storage:s});m.create('Public product',{name:'Example',photo:'data:image/png',patient:'Person',token:'secret'});m.append({question:'Public leaflet',answer:'Common headache'});assert.equal(new VueMemory({domain:'medivue',storage:s}).active(),null);assert.deepEqual(sanitizeFields({name:'Public',photo:'x',token:'abc',notes:'person@example.org'}),{name:'Public'});assert.throws(()=>m.append({question:'19900101-1234',answer:'x'}));assert.equal(m.active().turns.length,1)});
test('corrupt storage is recoverable without being overwritten; quota failures are atomic',()=>{const s=storage();s.setItem('vue-core-memory-v1:homevue','broken');const m=new VueMemory({domain:'homevue',storage:s});assert.equal(m.error,'corrupt');assert.equal(m.export(),'broken');assert.throws(()=>m.create('New'));m.reset();m.create('Plant');const previous=m.export();s.setItem=()=>{throw Error('quota')};assert.throws(()=>m.update({name:'Changed'}));assert.equal(m.export(),previous)});
test('backup import validates all rows and never overwrites good work with malformed data',()=>{const m=new VueMemory({domain:'wardrobevue'});m.create('Jacket');const previous=m.export(),bad=JSON.parse(previous);bad.cases.push({...bad.cases[0]});assert.throws(()=>m.import(bad));assert.equal(m.export(),previous);bad.domain='estatevue';assert.throws(()=>m.import(bad));m.remove(m.active().id);assert.equal(m.active(),null)});
test('memory limit is explicit and does not silently evict earlier cases',()=>{const m=new VueMemory({domain:'plantvue'});for(let i=0;i<50;i++)m.create('Plant '+i);assert.throws(()=>m.create('Extra'));assert.equal(m.db.cases.length,50)});
test('relevance selection retains older pertinent turns and strictly bounds model context',()=>{const turns=Array.from({length:20},(_,i)=>({question:i===0?'oak chair joinery':'unrelated '+i,answer:'x'.repeat(1800),kind:'ai_unverified',at:new Date().toISOString()}));const selected=selectHistory(turns,'oak chair joinery');assert.ok(selected.some(t=>t.question==='oak chair joinery'));assert.ok(selected.length<=4);assert.ok(selected.reduce((n,t)=>n+t.question.length+t.answer.length,0)<=4000);assert.match(memoryContext(selected,'antiqvue'),/UNTRUSTED DATA/);assert.match(memoryContext(selected,'antiqvue'),/Never reduce urgency/);assert.equal(memoryContext(selected,'medivue'),'');assert.equal(memoryContext([{question:'x',answer:'person@example.org'}],'antiqvue'),'')});
test('shared knowledge admits verified public passages only and strips private URL parameters',()=>{assert.equal(publicRecord('foodvue',{quote:'I think this is dangerous',url:'https://efsa.europa.eu/a'}),null);assert.equal(publicRecord('foodvue',{verifiedBy:'server_source_passage',quote:'a@example.org is mentioned',url:'https://efsa.europa.eu/a'}),null);assert.equal(publicURL('https://efsa.europa.eu.attacker.example/a'),null);assert.equal(publicURL('https://fass.se/a?token=secret&drug=example#x'),'https://fass.se/a?drug=example');const r=publicRecord('foodvue',{verifiedBy:'server_source_passage',quote:'Citric acid is E330.',url:'https://efsa.europa.eu/a'});assert.equal(r.domain,'foodvue');assert.ok(Number.isFinite(Date.parse(r.checkedAt)));assert.match(r.limits,/rechecking/)});
test('public archive writes and reads only domain-scoped passages and bounded atomic commands',async()=>{const old=globalThis.fetch,env={...process.env};process.env.UPSTASH_REDIS_REST_URL='https://redis.test';process.env.UPSTASH_REDIS_REST_TOKEN='test';let stored;globalThis.fetch=async(u,o)=>{const command=JSON.parse(o.body);assert.equal(u,'https://redis.test');assert.equal(command[3],'vue:knowledge:v1:foodvue');if(command.length>5){assert.match(command[1],/n>200/);stored=command[6];return Response.json({result:1})}return Response.json({result:[stored,JSON.stringify({...JSON.parse(stored),domain:'medivue'})]})};try{assert.equal(await collectPublicEvidence('foodvue',[{verifiedBy:'server_source_passage',quote:'Citric acid is E330.',url:'https://efsa.europa.eu/a'}]),true);const r=await readPublicEvidence('foodvue');assert.equal(r.entries.length,1);const response=await GET(new Request('https://local/api/vue-memory?domain=foodvue'));assert.equal((await response.json()).privateHistory,false)}finally{globalThis.fetch=old;process.env=env}});
test('all actual horse emergencies and persisted urgent caution override reassuring history without any model call',async()=>{for(const id of ['horseColic','horseChoke','horseBreathingDistress','horseSevereBleeding','horseUnableStand','horseNeuro','horseEyeTrauma','horseFoalingDifficulty','horseCannotBearWeight'])assert.match(urgentFollowup('anivue','Can I wait?',{selected:JSON.stringify([id])},'sv'),/akut/);assert.match(urgentFollowup('anivue','Looks fine',{emergencyCaution:'true'},'en'),/urgent/);const r=await POST(new Request('https://local',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain:'anivue',language:'sv',question:'Kan jag vänta?',fields:{selected:'["breathing"]'},history:[{question:'How is it?',answer:'No issue.'}]})}));assert.equal(r.status,200);assert.match((await r.json()).answer,/akut/);assert.match(urgentFollowup('motovue','What next?',{symptom:'brakes'},'sv'),/Kör inte/)});
test('follow-up provider receives bounded selected case context; budget failure makes no paid request',async()=>{const old=globalThis.fetch,env={...process.env};Object.assign(process.env,{UPSTASH_REDIS_REST_URL:'https://redis.test',UPSTASH_REDIS_REST_TOKEN:'test',OPENAI_API_KEY:'test',ANTIQVUE_DAILY_MODEL_CALL_LIMIT:'40'});let paid=0,exhausted=false;globalThis.fetch=async(u,o)=>{const b=JSON.parse(o.body);if(u==='https://redis.test')return Response.json({result:b[1].includes('INCR')?(exhausted?41:1):[]});paid++;assert.equal(b.store,false);assert.match(b.input,/Oak chair/);assert.match(b.input,/We already checked joinery/);assert.match(b.instructions,/no fresh web research/);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Next, inspect the underside marking.'}]}]})};const req=()=>new Request('https://local',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain:'antiqvue',language:'en',question:'What next?',fields:{description:'Oak chair'},history:[{question:'Joinery?',answer:'We already checked joinery'}]})});try{assert.equal((await POST(req())).status,200);exhausted=true;assert.equal((await POST(req())).status,429);assert.equal(paid,1)}finally{globalThis.fetch=old;process.env=env}});
test('MEDIVUE rejects generic personal follow-up and public knowledge rejects unknown domains',async()=>{const response=await POST(new Request('https://local',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain:'medivue',language:'en',question:'Change my dose?'})}));assert.equal(response.status,400);assert.equal((await GET(new Request('https://local/api/vue-memory?domain=unknown'))).status,400)});
