export const CATEGORIES={estatevue:['furniture','jewellery','vinyl','music','clothing','other'],wardrobevue:['clothing','shoes','bag','accessory','watch']};
export const PLANS=['review','keep','sell','donate','recycle'];
export const CONDITIONS=['unknown','new','good','worn','damaged'];
export function validateItem(raw,domain){if(!raw||!CATEGORIES[domain])throw Error('domain');const text=(k,max=300)=>typeof raw[k]==='string'?raw[k].trim().slice(0,max):'';const name=text('name',180);if(!name)throw Error('name');const id=text('id',80)||crypto.randomUUID();if(!/^[A-Za-z0-9_-]{1,80}$/.test(id))throw Error('id');return {id,name,category:CATEGORIES[domain].includes(raw.category)?raw.category:CATEGORIES[domain][0],location:text('location'),assigned:text('assigned'),brand:text('brand'),size:text('size',100),material:text('material'),model:text('model'),notes:text('notes',2000),condition:CONDITIONS.includes(raw.condition)?raw.condition:'unknown',plan:PLANS.includes(raw.plan)?raw.plan:'review',checked:raw.checked===true,wears:Number.isSafeInteger(raw.wears)&&raw.wears>=0&&raw.wears<=100000?raw.wears:0,price:typeof raw.price==='string'&&/^\d{1,7}(?:[.,]\d{1,2})?$/.test(raw.price)&&Number(raw.price.replace(',','.'))>0?raw.price.replace(',','.'):null,currency:['SEK','EUR','USD','GBP'].includes(raw.currency)?raw.currency:'SEK',report:text('report',12000)}}
export function needsReview(item){return !item.checked||item.condition==='unknown'}
export function mergeInventory(records,backup,domain){if(backup?.version!==1||backup.domain!==domain||!Array.isArray(backup.records)||backup.records.length>1000)throw Error('backup');const incoming=backup.records.map(r=>validateItem(r,domain)),ids=new Set(records.map(r=>r.id)),next=[...records];for(const item of incoming){if(ids.has(item.id))continue;ids.add(item.id);next.push(item)}if(next.length>1000)throw Error('limit');return next}
export function specialistFor(item){return {furniture:'antiqvue',jewellery:'antiqvue',vinyl:'vinylvue',music:'musicgearvue',clothing:'wardrobevue'}[item.category]||null}
export function itemDescription(item){return `${item.name}\nBrand: ${item.brand||'unknown'}; model / label: ${item.model||'unknown'}; size: ${item.size||'unknown'}; material: ${item.material||'unknown'}.\nOwner-reported condition: ${item.condition}.\n${item.notes}`.slice(0,3000)}
export function inventoryCSV(records){const fields=['name','category','location','assigned','brand','model','size','material','condition','wears','plan','checked','price','currency','notes'];const quote=v=>{let s=String(v??'');if(/^\s*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};return '\uFEFF'+[fields,...records.map(r=>fields.map(k=>r[k]))].map(row=>row.map(quote).join(',')).join('\r\n')}
