import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../api/vinylvue.js',import.meta.url),'utf8');
const api=await import('data:text/javascript;base64,'+Buffer.from(source.replaceAll("../core/memory-context.js",new URL("./memory-context.js",import.meta.url).href).replaceAll("../core/specialist-memory.js",new URL("./specialist-memory.js",import.meta.url).href)).toString('base64'));
const image='data:image/png;base64,'+Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]).toString('base64');
const req=(description='David Bowie Hunky Dory LSP-4623',action='value')=>new Request('https://www.vueapps.se/api/vinylvue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,description,language:'sv',action,currency:'SEK',market:'Sweden'})});
async function mocked(fetcher,run){const names=['OPENAI_API_KEY','KV_REST_API_URL','KV_REST_API_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN'];const before=Object.fromEntries(names.map(n=>[n,process.env[n]])),old=globalThis.fetch;process.env.OPENAI_API_KEY='test';process.env.KV_REST_API_URL='https://redis.example';process.env.KV_REST_API_TOKEN='test';delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.UPSTASH_REDIS_REST_TOKEN;globalThis.fetch=fetcher;try{await run()}finally{globalThis.fetch=old;for(const n of names)if(before[n]===undefined)delete process.env[n];else process.env[n]=before[n]}}
const reply=(report,sources=[])=>Response.json({status:'completed',output:[{type:'web_search_call',status:'completed',action:{sources}},{type:'message',content:[{type:'output_text',text:JSON.stringify(report)}]}]});
test('vinyl research links retain release names but never turn aggregate statistics into prices',()=>{const links=api.researchLinks([{url:'https://www.discogs.com/release/123-test?utm_source=x',title:'Bowie pressing'},{url:'https://www.discogs.com/release/123-test'},{url:'https://evil.example/discogs.com'},{url:'https://www.popsike.com/test.html',title:'Archive'}],[]);assert.equal(links.length,2);assert.equal(links[0].title,'Bowie pressing');assert.equal(links[0].url,'https://www.discogs.com/release/123-test');assert.ok(links.every(x=>!('amount' in x)));assert.equal(api.safeNarrative('Estimated value SEK 500'),'');assert.equal(api.safeNarrative('Catalogue LSP-4623; matrix unreadable'),'Catalogue LSP-4623; matrix unreadable')});
test('vinyl identifies provisionally with separate owner and photo evidence, empty sold range, live search and shared budget',async()=>{let calls=0;await mocked(async(url,options)=>{const b=JSON.parse(options.body);if(url==='https://redis.example'){assert.match(b[3],/antiqvue:global:/);return Response.json({result:1})}calls++;assert.equal(b.store,false);assert.equal(b.tool_choice,'required');assert.match(b.instructions,/Grade record and sleeve separately/);assert.match(b.instructions,/matrix\/runout/);assert.equal(b.input[0].content[1].image_url,image);return reply({exterior:'Ett omslag och en skiva syns.',analysis:'Pressningen är preliminär; etikett och matris behöver jämföras.',searchTerms:[],comparables:[]},[{url:'https://www.discogs.com/release/123-bowie',title:'Bowie release'}])},async()=>{const response=await api.POST(req());assert.equal(response.status,200);const d=await response.json();assert.equal(d.sections.length,4);assert.match(d.sections[2].body,/LSP-4623/);assert.equal(d.followUpQuestions.length,3);assert.match(d.followUpQuestions.join(' '),/provspelad/);assert.equal(d.valuation,null);assert.equal(d.researchSources[0].title,'Bowie release');assert.equal(calls,1)})});
test('a price range requires original sold-page verification and exact owner identifiers',async()=>{let pageCalls=0;const records=[200,300].map((amount,n)=>{const quote=`David Bowie Hunky Dory LSP-4623 Sold 2026-09-01 Hammer price SEK ${amount}`;return {title:'David Bowie Hunky Dory LSP-4623',url:'https://auctionet.com/en/'+(100+n),amount,currency:'SEK',date:'2026-09-01',kind:'sold',basis:'hammer',condition:'VG record and sleeve',evidence:{excerpt:quote,identity:'David Bowie Hunky Dory LSP-4623',price:'SEK '+amount,sold:'Sold',date:'2026-09-01',fees:'Hammer price'}}});await mocked(async(url)=>{if(url==='https://redis.example')return Response.json({result:1});if(url.startsWith('https://auctionet.com/')){pageCalls++;return new Response(records.find(c=>c.url===url).evidence.excerpt,{headers:{'Content-Type':'text/html'}})}return reply({exterior:'Skiva och omslag.',analysis:'Jämför katalog och etikett före slutlig identifiering.',searchTerms:['Bowie','Hunky Dory','LSP-4623'],comparables:records},records.map(c=>({url:c.url})))},async()=>{const d=await (await api.POST(req())).json();assert.equal(d.valuation.low,200);assert.equal(d.valuation.high,300);assert.equal(pageCalls,2);const unknown=await (await api.POST(req('Bowie album'))).json();assert.equal(unknown.valuation,null);assert.equal(pageCalls,2)})});
test('bad images and exhausted budget never reach the AI provider',async()=>{let provider=0;await mocked(async url=>{if(url==='https://redis.example')return Response.json({result:999});provider++;throw Error('unexpected')},async()=>{assert.equal((await api.POST(req())).status,429);assert.equal(provider,0);assert.equal(api.validImage('data:image/png;base64,aGVsbG8='),false)})});
