import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../api/vue-backlog.js',import.meta.url),'utf8'),api=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const secret='a-test-signing-secret-with-at-least-32-characters';
function cookie(overrides={}){const payload=Buffer.from(JSON.stringify({iss:'vueapps',aud:'vue-voting',sub:'member_123',exp:Math.floor(Date.now()/1000)+3600,...overrides})).toString('base64url');return 'vue_member='+payload+'.'+createHmac('sha256',secret).update(payload).digest('base64url')}
function request(body,headers={}){return new Request('https://www.vueapps.se/api/vue-backlog',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)})}
async function mocked(fetcher,run){const names=['VUE_MEMBER_SIGNING_SECRET','KV_REST_API_URL','KV_REST_API_TOKEN','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN','VUE_BACKLOG_ADMIN_TOKEN'];const before=Object.fromEntries(names.map(n=>[n,process.env[n]])),old=globalThis.fetch;process.env.VUE_MEMBER_SIGNING_SECRET=secret;process.env.KV_REST_API_URL='https://redis.example';process.env.KV_REST_API_TOKEN='test';delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.UPSTASH_REDIS_REST_TOKEN;delete process.env.VUE_BACKLOG_ADMIN_TOKEN;globalThis.fetch=fetcher;try{await run()}finally{globalThis.fetch=old;for(const n of names)if(before[n]===undefined)delete process.env[n];else process.env[n]=before[n]}}
test('membership cookies reject tampering, wrong audience, expiry and missing signing configuration',()=>{assert.equal(api.verifyMemberCookie(cookie(),secret),'member_123');assert.equal(api.verifyMemberCookie(cookie().replace('member','Member'),secret),null);assert.equal(api.verifyMemberCookie(cookie({aud:'other'}),secret),null);assert.equal(api.verifyMemberCookie(cookie({exp:1}),secret),null);assert.equal(api.verifyMemberCookie(cookie(),'short'),null);assert.equal(api.verifyMemberCookie(cookie()+'x',secret),null)});
test('client paid flags and unsigned accounts cannot vote or propose, with no database mutations',async()=>{let calls=0;await mocked(async()=>{calls++;throw Error('unexpected')},async()=>{assert.equal((await api.POST(request({action:'vote',id:'BOOKVUE',paid:true}))).status,403);assert.equal((await api.POST(request({action:'propose',name:'BOOKVUE',description:'Find rare books for readers.',paid:true}))).status,403);assert.equal(calls,0)})});
test('signed sessions still require an active unexpired server-side paid ledger',async()=>{for(const ledger of [null,{status:'inactive',paidUntil:Date.now()+10000},{status:'active',paidUntil:1}])await mocked(async(_,opts)=>{const cmd=JSON.parse(opts.body);assert.equal(cmd[0],'GET');return Response.json({result:ledger?JSON.stringify(ledger):null})},async()=>assert.equal((await api.POST(request({action:'vote',id:'BOOKVUE'},{Cookie:cookie()}))).status,403))});
test('same-origin protection and administrator authorization cannot be bypassed by paid membership',async()=>{await mocked(async()=>{throw Error('unexpected')},async()=>{assert.equal((await api.POST(request({action:'vote',id:'BOOKVUE'},{Cookie:cookie(),Origin:'https://evil.example'}))).status,403);assert.equal((await api.POST(request({action:'status',id:'BOOKVUE',status:'released'},{Cookie:cookie()}))).status,403)})});
test('proposal validation rejects existing VUEs, malformed names and empty descriptions',()=>{assert.equal(api.validateProposal({name:'VINYLVUE',description:'A vinyl application for people.'}),null);assert.equal(api.validateProposal({name:'<script>VUE',description:'A book application for people.'}),null);assert.equal(api.validateProposal({name:'BOOKVUE',description:'short'}),null);assert.equal(api.validateProposal({name:'bookvue',description:'Find rare books for readers.'}).name,'BOOKVUE')});
test('paid proposal writes durably with zero initial votes; duplicate proposals return conflict',async()=>{let writes=0;await mocked(async(_,opts)=>{const cmd=JSON.parse(opts.body);if(cmd[0]==='GET')return Response.json({result:JSON.stringify({status:'active',paidUntil:Date.now()+10000})});writes++;assert.equal(cmd[0],'EVAL');const item=JSON.parse(cmd.at(-1));assert.equal(item.votes,0);assert.equal(item.status,'proposed');assert.ok(!('member' in item));return Response.json({result:writes===1?'created':'duplicate'})},async()=>{const b={action:'propose',name:'BOOKVUE',description:'Find rare books for readers.'};assert.equal((await api.POST(request(b,{Cookie:cookie()}))).status,201);assert.equal((await api.POST(request(b,{Cookie:cookie()}))).status,409)})});
test('public backlog ranks votes without disclosing member identities',async()=>{await mocked(async(_,opts)=>{assert.equal(JSON.parse(opts.body)[0],'HGETALL');return Response.json({result:['BOOKVUE',JSON.stringify({id:'BOOKVUE',name:'BOOKVUE',description:'Books',votes:1,status:'proposed',createdAt:'2026-10-10'}),'GAMEVUE',JSON.stringify({id:'GAMEVUE',name:'GAMEVUE',description:'Games',votes:4,status:'planned',createdAt:'2026-10-10'})]})},async()=>{const d=await (await api.GET(new Request('https://www.vueapps.se/api/vue-backlog'))).json();assert.equal(d.items[0].id,'GAMEVUE');assert.equal(d.canVote,false);assert.ok(d.items.every(i=>!('member' in i)))})});
