import {eNumbers} from '../core/additives.js';
import {FOOD_TEXT} from './food-review-content.js';
const $=id=>document.getElementById(id),root=$('ingredient-review');let language=document.documentElement.lang||'en',busy=false,image=null,photoURL=null,version=0,rows=[],sources=[],aborter=null;
const t=i=>(FOOD_TEXT[language]||FOOD_TEXT.en)[i];
function status(i,extra=''){$('ingredient-status').textContent=t(i)+(extra?' '+extra:'');$('ingredient-status').className='status-message'}
function localize(){language=FOOD_TEXT[document.documentElement.lang]?document.documentElement.lang:'en';root.querySelectorAll('[data-f]').forEach(e=>e.textContent=t(Number(e.dataset.f)));if(rows.length)render();}
function link(url){const a=document.createElement('a');a.href=url;a.textContent=new URL(url).hostname+' ↗';a.target='_blank';a.rel='noopener noreferrer';return a}
function render(){$('ingredient-results').replaceChildren();for(const row of rows){const card=document.createElement('article');card.className='record';const h=document.createElement('h3');h.textContent=row.code+(row.name?' · '+row.name:'');card.append(h);if(row.type!=='official_passages_checked'){const p=document.createElement('p');p.textContent=t(13);card.append(p)}else{for(const [key,index]of [['identityQuote',14],['functionQuote',15],['riskQuote',16],['statusQuote',17],['adiQuote',18]]){const h4=document.createElement('h4');h4.textContent=t(index);const q=document.createElement('blockquote');q.textContent=row[key]||t(13);q.style.marginInlineStart='0';q.style.whiteSpace='pre-wrap';card.append(h4,q)}card.append(link(row.url));}$('ingredient-results').append(card)}if(sources.length){const h=document.createElement('h4');h.textContent=t(24);$('ingredient-results').append(h);for(const url of sources)$('ingredient-results').append(link(url),document.createTextNode(' · '))}$('ingredient-download').hidden=!rows.length}
function reset(){rows=[];sources=[];$('ingredient-results').replaceChildren();$('ingredient-download').hidden=true;}
function locked(value){busy=value;for(const control of root.querySelectorAll('input,textarea,button'))control.disabled=value;$('ingredient-read').disabled=value||!image;$('language').disabled=value;$('ingredient-stop').hidden=!value;$('ingredient-stop').disabled=false;}
async function request(body){const r=await fetch('/api/foodvue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,confirmed:true,language}),signal:AbortSignal.any([aborter.signal,AbortSignal.timeout(60000)])});if(!r.ok)throw Error('api');return r.json()}
$('ingredient-photo').onchange=async()=>{const v=++version;image=null;reset();$('ingredient-read').disabled=true;$('ingredient-confirmed').checked=false;$('ingredient-preview').replaceChildren();if(photoURL)URL.revokeObjectURL(photoURL);photoURL=null;const file=$('ingredient-photo').files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){status(10);return}photoURL=URL.createObjectURL(file);try{const img=new Image();img.src=photoURL;img.alt=t(3);await img.decode();if(v!==version)return;const scale=Math.min(1,1800/img.naturalWidth,1800/img.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);image=canvas.toDataURL('image/jpeg',0.9);if(image.length>4*1024*1024)throw Error('size');$('ingredient-preview').append(img);$('ingredient-read').disabled=false;status(28)}catch{if(v===version)status(10)}};
$('ingredient-label').oninput=()=>{reset();$('ingredient-confirmed').checked=false;$('ingredient-status').textContent=''};
$('ingredient-read').onclick=async()=>{if(busy||!image)return;if(!$('ingredient-confirmed').checked){status(10);return}aborter=new AbortController();locked(true);reset();status(9);try{const result=await request({action:'read',image});$('ingredient-label').value=result.label||'';$('ingredient-confirmed').checked=false;status(22)}catch{status(aborter?.signal.aborted?31:11)}finally{locked(false)}};
$('ingredient-scan').onclick=()=>{if(busy)return;const codes=eNumbers($('ingredient-label').value);reset();rows=codes.map(code=>({code,type:'unverified'}));render();status(codes.length?25:12,codes.length?codes.join(', '):'')};
$('ingredient-research').onclick=async()=>{if(busy)return;const label=$('ingredient-label').value.trim(),codes=eNumbers(label);if(!label||!$('ingredient-confirmed').checked){status(10);return}if(!codes.length){reset();status(12);return}if(codes.length>80){status(10);return}aborter=new AbortController();locked(true);reset();rows=codes.map(code=>({code,type:'unverified'}));render();status(9);try{for(let offset=0;offset<codes.length;offset+=8){const result=await request({action:'review',label,batch:codes.slice(offset,offset+8)});for(const row of result.entries||[]){const index=rows.findIndex(x=>x.code===row.code);if(index>=0)rows[index]=row}sources=[...new Set([...sources,...(result.links||[]).map(x=>x.url)])];render();status(27,Math.min(offset+8,codes.length)+' / '+codes.length)}}catch{status(aborter?.signal.aborted?31:11)}finally{locked(false)}};
$('ingredient-stop').onclick=()=>aborter?.abort();
$('ingredient-clear').onclick=()=>{if(busy)return;++version;image=null;if(photoURL)URL.revokeObjectURL(photoURL);photoURL=null;$('ingredient-photo').value='';$('ingredient-label').value='';$('ingredient-preview').replaceChildren();$('ingredient-confirmed').checked=false;$('ingredient-read').disabled=true;reset();$('ingredient-status').textContent=''};
$('ingredient-download').onclick=()=>{const text=[t(20),...rows.map(row=>[row.code,row.name||t(13),...['identityQuote','functionQuote','riskQuote','statusQuote','adiQuote'].map(k=>row[k]||''),row.url||''].filter(Boolean).join('\n\n'))].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='foodvue-ingredient-review.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('language').addEventListener('change',()=>{if(busy){$('language').value=language;return}$('ingredient-status').textContent='';localize()});
const observer=new MutationObserver(()=>{if(!busy)localize()});observer.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
window.addEventListener('pagehide',()=>{if(photoURL)URL.revokeObjectURL(photoURL);aborter?.abort();observer.disconnect()});localize();
