import {TEXT,CATEGORIES} from './medivue-content.js';
import {localizeLanguagePicker} from './content.js';
const $=id=>document.getElementById(id),fields=['name','strength','form','country','leaflet'];let language='en',busy=false,imageReady=false,version=0,selection=null,reportText='';
const t=i=>TEXT[language][i],ctx=$('canvas').getContext('2d');
const identified=s=>/(?:\b(?:19|20)?\d{6}[-+ ]?\d{4}\b|[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|\b(?:patient|personnummer|personal identity|social security|patientnamn|receptnummer)\s*[:#]|\b(?:\+46|0046)[\s\d()-]{7,})/i.test(s);
function invalidate(){reportText='';$('report').replaceChildren();$('download').hidden=true}
function notice(i){$('notice').textContent=t(i);$('notice').className='status-message'}
function render(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';$('language').value=language;localizeLanguagePicker($('language'),language);document.querySelectorAll('[data-m]').forEach(e=>e.textContent=t(Number(e.dataset.m)));$('photo-state').textContent=t(imageReady?33:35);$('references').replaceChildren();for(const [name,url]of [['FASS','https://fass.se/'],['Läkemedelsverket','https://www.lakemedelsverket.se/'],['EMA','https://www.ema.europa.eu/en/medicines']])$('references').append(link(name,url),document.createTextNode(' · '));}
function link(title,url){const a=document.createElement('a');a.href=url;a.textContent=title;a.target='_blank';a.rel='noopener noreferrer';return a}
function locked(value){busy=value;for(const e of document.querySelectorAll('input,textarea,select,button'))e.disabled=value;$('identify').disabled=value||!imageReady}
async function request(body){if(busy)return null;if(!$('privacy').checked||fields.some(k=>identified($(k).value))){notice(16);return null}locked(true);invalidate();notice(15);try{const r=await fetch('/api/medivue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,privacyConfirmed:true,language}),signal:AbortSignal.timeout(60000)});if(!r.ok){notice(r.status===400?16:17);return null}$('notice').textContent='';return await r.json()}catch{notice(17);return null}finally{locked(false)}}
$('photo').onchange=async()=>{const v=++version;invalidate();imageReady=false;selection=null;$('privacy').checked=false;$('confirmed').checked=false;$('canvas').hidden=true;$('identify').disabled=true;const file=$('photo').files[0];if(!file){render();return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){notice(16);return}const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(v!==version)return;const scale=Math.min(1,1800/img.naturalWidth,1800/img.naturalHeight);$('canvas').width=Math.max(1,Math.round(img.naturalWidth*scale));$('canvas').height=Math.max(1,Math.round(img.naturalHeight*scale));ctx.fillStyle='#fff';ctx.fillRect(0,0,$('canvas').width,$('canvas').height);ctx.drawImage(img,0,0,$('canvas').width,$('canvas').height);imageReady=true;$('canvas').hidden=false;$('identify').disabled=false;render();notice(33)}catch{notice(16)}finally{URL.revokeObjectURL(url)}};
function position(event){const r=$('canvas').getBoundingClientRect();return {x:Math.max(0,Math.min($('canvas').width,(event.clientX-r.left)*$('canvas').width/r.width)),y:Math.max(0,Math.min($('canvas').height,(event.clientY-r.top)*$('canvas').height/r.height))}}
$('canvas').onpointerdown=e=>{if(busy||!imageReady)return;selection=position(e);$('canvas').setPointerCapture(e.pointerId)};
$('canvas').onpointerup=e=>{if(busy||!selection)return;const end=position(e),x=Math.min(selection.x,end.x),y=Math.min(selection.y,end.y),w=Math.abs(end.x-selection.x),h=Math.abs(end.y-selection.y);selection=null;if(w<3||h<3)return;ctx.fillStyle='#000';ctx.fillRect(Math.floor(x)-2,Math.floor(y)-2,Math.ceil(w)+4,Math.ceil(h)+4);$('privacy').checked=false;$('confirmed').checked=false;invalidate();notice(33)};
$('canvas').onpointercancel=()=>selection=null;
$('identify').onclick=async()=>{if(!imageReady||busy)return;const image=$('canvas').toDataURL('image/jpeg',0.9);if(image.length>4*1024*1024){notice(16);return}const result=await request({action:'identify',image});if(!result)return;for(const k of ['name','strength','form','leaflet'])$(k).value=result[k]||'';$('confirmed').checked=false;notice(18)};
const frequencies=['very_common','common','uncommon','rare','very_rare','unknown'],actions=['urgent','contact','unspecified'];
function show(result){invalidate();const host=$('report');function paragraph(text){const p=document.createElement('p');p.textContent=text;host.append(p);reportText+=text+'\n\n'}
 if(!result.matched||!result.effects?.length)paragraph(t(19));
 if(result.source){paragraph(t(result.source.type==='user_supplied_unverified'?24:25));paragraph(result.source.identityQuote);if(result.source.url){host.append(link(t(26),result.source.url));reportText+=result.source.url+'\n'}}
 for(const row of [...result.effects||[]].sort((a,b)=>actions.indexOf(a.action)-actions.indexOf(b.action))){const card=document.createElement('article');card.className='record'+(row.action==='urgent'?' urgent':'');const h=document.createElement('h3');h.textContent=row.effect;const info=document.createElement('p');info.textContent=t(21)+': '+CATEGORIES[language][Math.max(0,frequencies.indexOf(row.frequency))]+' · '+t(22)+': '+CATEGORIES[language][6+Math.max(0,actions.indexOf(row.action))];const quote=document.createElement('blockquote');quote.textContent=row.excerpt;card.append(h,info,quote);host.append(card);reportText+=h.textContent+'\n'+info.textContent+'\n'+row.excerpt+'\n\n'}
 if(result.links?.length){paragraph(t(27));for(const s of result.links){try{const u=new URL(s.url);if(u.protocol!=='https:')continue;host.append(link(u.hostname,u.href),document.createElement('br'));reportText+=u.href+'\n'}catch{}}}
 paragraph(t(20));$('download').hidden=!reportText;
}
$('review').onclick=async()=>{if(busy)return;if(!$('confirmed').checked||fields.slice(0,4).some(k=>!$(k).value.trim())){notice(16);return}const result=await request({action:'review',...Object.fromEntries(fields.map(k=>[k,$(k).value.trim()])),identityConfirmed:true});if(result)show(result)};
for(const k of fields)$(k).oninput=()=>{invalidate();$('confirmed').checked=false;$('privacy').checked=false;$('notice').textContent=''};
$('language').onchange=()=>{if(busy||!TEXT[$('language').value])return;language=$('language').value;invalidate();$('notice').textContent='';render()};
$('clear').onclick=()=>{if(busy)return;++version;selection=null;imageReady=false;ctx.clearRect(0,0,$('canvas').width,$('canvas').height);$('canvas').width=1;$('canvas').height=1;$('canvas').hidden=true;for(const k of fields)$(k).value=k==='country'?'Sweden':'';$('photo').value='';$('privacy').checked=false;$('confirmed').checked=false;$('identify').disabled=true;invalidate();$('notice').textContent='';render()};
$('download').onclick=()=>{if(!reportText)return;const url=URL.createObjectURL(new Blob([reportText],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='medivue-leaflet-review.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
render();
