import {VueMemory,MEMORY_DOMAINS,sanitizeFields} from '../core/memory.js';
import {MEMORY_TEXT} from './memory-content.js';
const domain=document.body.dataset.domain||location.pathname.split('/').pop().replace('.html','');
if(MEMORY_DOMAINS.includes(domain))init();
function init(){
 const $=id=>document.getElementById(id),session=domain==='medivue';let storage=null;try{storage=localStorage}catch{}
 const store=new VueMemory({domain,storage,persistent:!session}),originalFetch=globalThis.fetch.bind(globalThis);let enabled=true,useHistory=true,inflight=0,restoring=false,pending=null,epoch=0,aniState={},lastLocal='',knowledge=[];
 try{if(!session)enabled=storage?.getItem('vue-core-memory-enabled:'+domain)!=='false'}catch{}
 const panel=document.createElement('section');panel.id='vue-memory';panel.className='panel';panel.style.cssText='max-width:1100px;margin:28px auto;padding:24px;border:1px solid #71818a;border-radius:16px;overflow-wrap:anywhere';
 panel.innerHTML='<h2 data-memory="0"></h2><label><input id="vue-memory-enabled" type="checkbox" style="width:auto"> <span data-memory="1"></span></label><p id="vue-memory-scope"></p><p data-memory="10"></p><label for="vue-memory-title" data-memory="2"></label><input id="vue-memory-title" maxlength="120" autocomplete="off"><button id="vue-memory-new" type="button" class="quiet" data-memory="3"></button><label for="vue-memory-cases" data-memory="4"></label><select id="vue-memory-cases"></select><div class="toolbar"><button id="vue-memory-resume" type="button" class="quiet" data-memory="5"></button><button id="vue-memory-delete" type="button" class="quiet" data-memory="6"></button><button id="vue-memory-export" type="button" class="quiet" data-memory="7"></button><label for="vue-memory-import" data-memory="8"></label><input id="vue-memory-import" type="file" accept="application/json,.json"><button id="vue-memory-reset" type="button" class="quiet" data-memory="24"></button></div><label><input id="vue-memory-use" type="checkbox" checked style="width:auto"> <span data-memory="19"></span></label><div id="vue-memory-status" role="status" aria-live="polite"></div><details><summary data-memory="9"></summary><div id="vue-memory-history"></div></details><section id="vue-memory-followup"><h3 data-memory="34"></h3><label for="vue-memory-question" data-memory="35"></label><textarea id="vue-memory-question" maxlength="3000" rows="3"></textarea><button id="vue-memory-ask" type="button" data-memory="36"></button><div id="vue-memory-answer" style="white-space:pre-wrap" aria-live="polite"></div><p data-memory="39"></p></section><p id="vue-memory-medical" data-memory="40" hidden></p><details id="vue-memory-knowledge"><summary data-memory="20"></summary><div id="vue-memory-sources"></div></details><p data-memory="22"></p><p data-memory="33"></p>';
 window.vueCoreMemory={domain,getFields:()=>store.active()?.fields||{},getCaseId:()=>store.db.active};
 const root=$('root');if(root)root.after(panel);else(document.querySelector('main')||document.body).append(panel);
 const style=document.createElement('style');style.textContent='#vue-memory label{display:block;margin-top:14px}#vue-memory input:not([type=checkbox]),#vue-memory select,#vue-memory textarea{display:block;width:100%;max-width:100%;padding:10px;border:1px solid #71818a;border-radius:7px;background:transparent;color:inherit}#vue-memory button{margin:8px 5px 8px 0;padding:9px 12px;cursor:pointer}#vue-memory .toolbar{display:flex;flex-wrap:wrap;gap:6px}#vue-memory article{border-bottom:1px solid #71818a;padding:12px 0}#vue-memory blockquote{white-space:pre-wrap;overflow-wrap:anywhere;margin-inline:8px}#vue-memory h2{font-size:24px}#vue-memory p{font-size:14px;line-height:1.6}';document.head.append(style);
 const t=i=>(MEMORY_TEXT[document.documentElement.lang]||MEMORY_TEXT.en)[i];
 function message(i){$('vue-memory-status').textContent=t(i)}
 function snapshot(){if(domain==='anivue')return sanitizeFields(aniState);const fields={};const ids=session?['name','strength','form','country']:domain==='anyvue'?['question']:domain==='motovue'?['vehicle','symptom','notes']:domain==='foodvue'?['ingredient-label','recipe','category','original','target']:domain==='slumpvue'?[]:['description','market','currency','name','category','notes','brand','size','material','model','condition','plan','location','interval','due','last'];for(const id of ids){const el=$(id);if(el&&el.value!==undefined)fields[id]=el.value}if(domain==='foodvue')try{const raw=storage?.getItem('vueapps-foodvue-v1');if(raw&&raw.length<=20000)fields.recipeState=raw}catch{}const itemId=store.active()?.fields.itemId;if(itemId&&!fields.name&&['estatevue','wardrobevue'].includes(domain))return store.active().fields;if(itemId)fields.itemId=itemId;return sanitizeFields(fields)}
 function scheduleSave(){clearTimeout(pending);const token=epoch;pending=setTimeout(()=>{if(token===epoch)safeSave()},350)}
 function safeSave(){if(!enabled||restoring||store.error==='corrupt')return;try{if(!store.active())store.create($('vue-memory-title').value||snapshot().name||snapshot().recipe||snapshot().description?.slice(0,70)||domain.toUpperCase());store.update(snapshot());renderCases();message(26)}catch{message(13)}}
 function renderCases(){const chosen=$('vue-memory-cases').value||store.db.active;$('vue-memory-cases').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=t(15);$('vue-memory-cases').append(placeholder);for(const c of [...store.db.cases].sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt))){const o=document.createElement('option');o.value=c.id;o.textContent=c.title+' · '+new Date(c.updatedAt).toLocaleDateString(document.documentElement.lang);$('vue-memory-cases').append(o)}$('vue-memory-cases').value=store.db.cases.some(c=>c.id===chosen)?chosen:store.db.active||'';}
 function renderHistory(){const active=store.active();$('vue-memory-history').replaceChildren();for(const turn of [...active?.turns||[]].reverse()){const a=document.createElement('article'),p=document.createElement('p'),q=document.createElement('blockquote'),r=document.createElement('blockquote');p.textContent=new Date(turn.at).toLocaleString(document.documentElement.lang)+' · '+t(turn.kind==='research_passages'?18:turn.kind==='ai_unverified'?16:17);q.textContent=t(28)+': '+turn.question;r.textContent=t(29)+': '+turn.answer;a.append(p,q,r);$('vue-memory-history').append(a)}}
 function render(){panel.querySelectorAll('[data-memory]').forEach(el=>el.textContent=t(Number(el.dataset.memory)));$('vue-memory-scope').textContent=t(session?12:11);$('vue-memory-enabled').checked=enabled;$('vue-memory-enabled').parentElement.hidden=session;$('vue-memory-use').checked=useHistory;$('vue-memory-use').parentElement.hidden=session;$('vue-memory-followup').hidden=session;$('vue-memory-medical').hidden=!session;for(const el of panel.querySelectorAll('button,input,select,textarea'))el.disabled=inflight>0;if(session)$('vue-memory-import').disabled=true;renderCases();renderHistory();}
 function restore(fields){restoring=true;if(domain==='anivue')aniState=sanitizeFields(fields);epoch++;clearTimeout(pending);try{for(const el of document.querySelectorAll('input[type=file]'))if(!panel.contains(el)){el.value='';el.dispatchEvent(new Event('change',{bubbles:true}))}window.dispatchEvent(new CustomEvent('vue:restore',{detail:{domain,fields}}));for(const [id,value]of Object.entries(fields)){const el=$(id);if(!el||panel.contains(el)||el.type==='file'||el.type==='checkbox'||el.type==='password')continue;el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}}finally{restoring=false}render();message(14)}
 function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function record(question,answer,kind='ai_unverified',caseId=store.db.active,startEpoch=epoch){if(!enabled||restoring||epoch!==startEpoch)return;try{if(caseId&&store.db.active!==caseId)return;if(!store.active())store.create(question.slice(0,70)||domain.toUpperCase());store.append({question,answer,kind});store.update(snapshot());render();message(26)}catch{message(13)}}
 function answerText(data){if(typeof data.analysis==='string')return data.analysis;if(typeof data.synthesis==='string')return data.synthesis;if(typeof data.answer==='string')return data.answer;if(data.effects)return data.effects.map(e=>e.effect+'\n'+e.excerpt).join('\n\n');if(data.entries)return data.entries.map(e=>[e.code,e.name,e.identityQuote,e.functionQuote,e.riskQuote,e.statusQuote,e.adiQuote,e.type].filter(Boolean).join('\n')).join('\n\n');if(data.visibleObservations)return JSON.stringify(data);return ''}
 const routes=new Set(['/api/'+domain,domain==='anivue'?'/api/analyze-animal':'/api/'+domain,'/api/vue-followup']);
 globalThis.fetch=async function(input,options){let path,body;try{const url=new URL(typeof input==='string'?input:input.url,location.href);if(url.origin!==location.origin&&!(domain==='anivue'&&url.origin==='https://www.vueapps.se'&&url.pathname==='/api/vue-followup'))return originalFetch(input,options);path=url.pathname;if(!routes.has(path)||options?.method?.toUpperCase()!=='POST'||typeof options.body!=='string')return originalFetch(input,options);body=JSON.parse(options.body)}catch{return originalFetch(input,options)}
 const question=body.question||body.description||body.label||[body.name,body.strength,body.form,body.country].filter(Boolean).join(' ')||JSON.stringify(snapshot());
 const startEpoch=epoch;let caseId=store.db.active;if(enabled&&!store.active()&&!session){try{store.create(question.slice(0,70)||domain.toUpperCase(),snapshot());caseId=store.db.active}catch{message(13)}}
 if(enabled&&useHistory&&!session&&path!=='/api/vue-followup')body.history=store.history(question);
 inflight++;render();try{const response=await originalFetch(input,{...options,body:JSON.stringify(body)});if(response.ok&&body.action!=='identify'&&body.action!=='read'){try{const data=await response.clone().json(),answer=answerText(data);if(answer&&(!session||data.matched===true))record(session?'Public leaflet review':question,answer,data.source?.type==='official_page_passages_verified'||data.entries?'research_passages':'ai_unverified',caseId,startEpoch)}catch{}}return response}finally{inflight--;render()}};
 $('vue-memory-enabled').onchange=()=>{enabled=$('vue-memory-enabled').checked;try{storage?.setItem('vue-core-memory-enabled:'+domain,String(enabled))}catch{message(13)}if(enabled)safeSave();else message(31)};
 $('vue-memory-use').onchange=()=>useHistory=$('vue-memory-use').checked;
 $('vue-memory-new').onclick=()=>{if(inflight)return;const title=$('vue-memory-title').value.trim();if(!title){message(27);return}try{store.create(title);epoch++;restoring=true;if(domain==='anivue')aniState={};for(const el of document.querySelectorAll('input[type=file]'))if(!panel.contains(el)){el.value='';el.dispatchEvent(new Event('change',{bubbles:true}))}window.dispatchEvent(new CustomEvent('vue:new-case',{detail:{domain}}));if(domain!=='anivue'&&domain!=='foodvue')for(const id of Object.keys(snapshot())){const el=$(id);if(el&&['text','textarea'].includes(el.type)){el.value='';el.dispatchEvent(new Event('input',{bubbles:true}))}}restoring=false;store.update(snapshot());render();$('vue-memory-answer').textContent='';message(26)}catch{restoring=false;message(13)}};
 $('vue-memory-resume').onclick=()=>{if(inflight)return;try{if(store.active())store.update(snapshot());store.switch($('vue-memory-cases').value);restore(store.active().fields)}catch{message(13)}};
 $('vue-memory-delete').onclick=()=>{if(inflight||!$('vue-memory-cases').value)return;if(!window.confirm(t(25)))return;try{epoch++;clearTimeout(pending);store.remove($('vue-memory-cases').value);render()}catch{message(13)}};
 $('vue-memory-reset').onclick=()=>{if(inflight||!window.confirm(t(25)))return;try{epoch++;clearTimeout(pending);store.reset();render();$('vue-memory-answer').textContent='';$('vue-memory-status').textContent=''}catch{message(13)}};
 $('vue-memory-export').onclick=()=>download(store.export(),'core-vue-'+domain+'-memory.json');
 $('vue-memory-import').onchange=async()=>{const file=$('vue-memory-import').files[0];if(!file||session||inflight)return;try{if(file.size>1000000)throw Error('size');store.import(JSON.parse(await file.text()));render();message(26)}catch{message(13)}finally{$('vue-memory-import').value=''}};
 $('vue-memory-ask').onclick=async()=>{const question=$('vue-memory-question').value.trim();if(session||inflight||question.length<3)return;safeSave();const history=enabled&&useHistory?store.history(question):[];const fields=enabled&&useHistory?snapshot():{};inflight++;render();message(37);try{const endpoint=domain==='anivue'?'https://www.vueapps.se/api/vue-followup':'/api/vue-followup';const r=await globalThis.fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',body:JSON.stringify({domain,question,history,fields,language:document.documentElement.lang}),signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('api');const result=await r.json();if(typeof result.answer!=='string'||!result.answer.trim())throw Error('answer');$('vue-memory-answer').textContent=result.answer;record(question,result.answer);$('vue-memory-status').textContent=''}catch{message(38)}finally{inflight--;render()}};
 document.addEventListener('input',event=>{if(panel.contains(event.target)||restoring||!enabled||session)return;scheduleSave()});
 document.addEventListener('change',event=>{if(panel.contains(event.target)||restoring||!enabled||session||event.target.type==='file')return;scheduleSave()});
 window.addEventListener('vue:case-select',event=>{const d=event.detail;if(d?.domain!==domain||!enabled)return;try{epoch++;clearTimeout(pending);const known=store.db.cases.find(c=>c.fields.itemId===d.itemId);if(known)store.switch(known.id);else if(store.active()&&!store.active().fields.itemId)store.update({...snapshot(),itemId:d.itemId});else store.create(d.title,{...snapshot(),itemId:d.itemId});store.update({...snapshot(),itemId:d.itemId});render()}catch{message(13)}});
 window.addEventListener('vue:case-record',event=>{const d=event.detail;if(d?.domain===domain)record(d.question,d.answer,'local_guidance')});
 window.addEventListener('vue:new-item',event=>{if(event.detail?.domain!==domain||!enabled)return;try{epoch++;clearTimeout(pending);store.commit({...store.db,active:null});render()}catch{message(13)}});
 window.addEventListener('vue:state',event=>{if(event.detail?.domain!==domain)return;aniState=sanitizeFields(event.detail.fields);if(!restoring&&enabled){scheduleSave()}});
 document.addEventListener('click',event=>{if(panel.contains(event.target)||restoring||!enabled)return;const id=event.target.closest('button')?.id;if(session&&id==='clear'){epoch++;clearTimeout(pending);store.reset();render();return}if(domain==='slumpvue'&&['go','again'].includes(id))queueMicrotask(()=>record($('result-title')?.textContent||'', $('result-body')?.textContent||'','local_guidance'));if(['antiqvue','musicgearvue','vinylvue'].includes(domain)&&id==='prepare')queueMicrotask(()=>record(snapshot().description||'', $('result')?.textContent||'','draft'))});
 const outputs=new MutationObserver(()=>{if(restoring||inflight||!enabled)return;clearTimeout(pending);const token=epoch;pending=setTimeout(()=>{if(token!==epoch)return;const node=domain==='motovue'?$('result'):domain==='foodvue'?$('shopping'):null;const text=node?.textContent?.trim();if(text&&text!==lastLocal&&(!node.hidden)){lastLocal=text;record(JSON.stringify(snapshot()),text,'local_guidance')}},100)});
 function watchOutputs(){outputs.disconnect();const node=domain==='motovue'?$('result'):domain==='foodvue'?$('plan'):null;if(node)outputs.observe(node,{childList:true,subtree:true,characterData:true})}
 const languageObserver=new MutationObserver(()=>{render();watchOutputs()});languageObserver.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
 $('vue-memory-knowledge').ontoggle=async()=>{if(!$('vue-memory-knowledge').open||knowledge.length)return;try{const url=(domain==='anivue'?'https://www.vueapps.se':'')+'/api/vue-memory?domain='+domain;const r=await originalFetch(url,{credentials:'omit',signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('source');const d=await r.json();$('vue-memory-sources').replaceChildren();knowledge=d.entries||[];for(const row of knowledge){const a=document.createElement('article'),date=document.createElement('p'),quote=document.createElement('blockquote'),link=document.createElement('a');date.textContent=row.checkedAt;quote.textContent=row.quote;link.href=row.url;link.textContent=t(21);link.target='_blank';link.rel='noopener noreferrer';a.append(date,quote,link);$('vue-memory-sources').append(a)}for(const [title,url]of d.references||[]){const a=document.createElement('a');a.href=url;a.textContent=title+' ↗';a.target='_blank';a.rel='noopener noreferrer';$('vue-memory-sources').append(a,document.createTextNode(' · '))}if(!d.available){const p=document.createElement('p');p.textContent=t(23);$('vue-memory-sources').append(p)}}catch{$('vue-memory-sources').textContent=t(23)}};
 window.addEventListener('pagehide',()=>{clearTimeout(pending);if(enabled&&!restoring&&!session&&store.active())try{store.update(snapshot())}catch{}outputs.disconnect();languageObserver.disconnect()});
 render();watchOutputs();if(store.error)message(13);if(enabled&&!session){if(document.body.dataset.handoff==='true'){try{store.create(snapshot().name||snapshot().description?.slice(0,70)||domain.toUpperCase(),snapshot());render()}catch{message(13)}}else if(store.active())restore(store.active().fields)}
 window.dispatchEvent(new CustomEvent('vue:memory-ready',{detail:{domain,fields:store.active()?.fields||{}}}));
}
