import {UI,DETAILS} from './possessions-content.js';
import {CATEGORIES,PLANS,CONDITIONS,validateItem,needsReview,mergeInventory,specialistFor,itemDescription,inventoryCSV} from '../core/possessions.js';
import {prepareHandoff,consumeHandoff} from '../core/handoff.js';
import {specialistGuide} from '../core/specialists.js';
import {localizeLanguagePicker} from './content.js';
const RANGE={"en": "Observed comparable sold-price range — not a certified valuation", "sv": "Observerat slutprisintervall för jämförelseobjekt — inte en certifierad värdering", "es": "Rango observado de ventas comparables — no es tasación certificada", "hi": "तुलनीय बिक्री का देखा गया मूल्य अंतराल — प्रमाणित मूल्यांकन नहीं", "zh-CN": "可比成交价格区间 — 非认证估价", "ru": "Диапазон цен проданных аналогов — не сертифицированная оценка", "ar": "نطاق أسعار مبيعات مشابهة — ليس تقييماً معتمداً"};
const CONTEXT={"en": "Retrieved research sources — sale prices not verified", "sv": "Hämtade undersökningskällor — slutpriser inte verifierade", "es": "Fuentes consultadas — precios de venta no verificados", "hi": "शोध स्रोत — बिक्री मूल्य सत्यापित नहीं", "zh-CN": "研究来源 — 未核实成交价", "ru": "Источники — цены продаж не проверены", "ar": "مصادر البحث — أسعار البيع غير موثقة"};
const domain=document.body.dataset.domain,wardrobe=domain==='wardrobevue',key='vueapps-'+domain+'-v1',$=id=>document.getElementById(id),picker=$('language');
let language='en',records=[],editing=null,removed=null,image=null,photoURL=null,report='',busy=false,selection=0,loadError=false;
try{const saved=localStorage.getItem(key+'-language');if(UI[saved])language=saved;const raw=localStorage.getItem(key);if(raw)records=mergeInventory([],JSON.parse(raw),domain)}catch{loadError=true}
const t=()=>UI[language],details=()=>DETAILS[language][wardrobe?1:0],fields=['name','category','location','assigned','brand','size','material','model','condition','wears','price','currency','notes','plan'];
$('editor').innerHTML=`<form id="item-form"><label for="name" data-p="1"></label><input id="name" maxlength="180" required><label for="category" data-p="2"></label><select id="category"></select><label for="location" data-p="3"></label><input id="location" maxlength="300"><label for="assigned" data-p="4"></label><input id="assigned" maxlength="300"><label for="brand" data-p="5"></label><input id="brand" maxlength="300"><div class="two"><div><label for="size" data-p="6"></label><input id="size" maxlength="100"></div><div><label for="material" data-p="7"></label><input id="material" maxlength="300"></div></div><label for="model" data-p="8"></label><input id="model" maxlength="300"><label for="condition" data-p="9"></label><select id="condition"></select><label for="plan" data-p="15"></label><select id="plan"></select><label><input id="checked" type="checkbox"> <span data-p="21"></span></label><div id="wear-editor"><label for="wears" data-p="22"></label><input id="wears" type="number" min="0" max="100000" step="1" value="0"></div><label for="price" data-p="23"></label><div class="two"><input id="price" inputmode="decimal" pattern="[0-9]{1,7}([.,][0-9]{1,2})?" maxlength="10"><select id="currency" aria-label="Currency"><option>SEK</option><option>EUR</option><option>USD</option><option>GBP</option></select></div><label for="notes" data-p="24"></label><textarea id="notes" maxlength="2000" rows="4"></textarea><label><input id="attach" type="checkbox"> <span data-p="55"></span></label><div class="toolbar"><button type="submit" class="primary" data-p="25"></button><button type="button" id="new" class="quiet" data-p="26"></button></div></form>`;
for(const [id,values]of [['category',CATEGORIES[domain]],['condition',CONDITIONS],['plan',PLANS]])for(const value of values){const option=document.createElement('option');option.value=value;$(id).append(option)}
$('wear-editor').hidden=!wardrobe;$('analyze').hidden=!wardrobe;
function notify(index){$('notice').className='status-message';$('notice').textContent=t()[index]}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function save(next){records=next;try{localStorage.setItem(key,JSON.stringify({version:1,domain,records}));notify(40)}catch{notify(41)}render()}
function resetPhoto(){selection++;image=null;report='';$('report').replaceChildren();$('photo').value='';$('preview').replaceChildren();$('analyze').disabled=true;if(photoURL)URL.revokeObjectURL(photoURL);photoURL=null}
function reset(){$('item-form').reset();editing=null;resetPhoto()}
function current(){const raw=Object.fromEntries(fields.map(k=>[k,$(k).value]));raw.wears=Number(raw.wears);raw.checked=$('checked').checked;raw.id=editing||undefined;raw.report=$('attach').checked?report:records.find(r=>r.id===editing)?.report||'';const item=validateItem(raw,domain);if(raw.price&&!item.price)throw Error('price');return item}
function saleDraft(item){return [t()[44],item.name,t()[5]+': '+(item.brand||t()[10]),t()[8]+': '+(item.model||t()[10]),t()[6]+': '+(item.size||t()[10]),t()[7]+': '+(item.material||t()[10]),t()[9]+': '+t()[10+CONDITIONS.indexOf(item.condition)],t()[45],needsReview(item)?t()[57]:'',t()[24]+': '+(item.notes||'—'),t()[23]+': '+(item.price?item.price+' '+item.currency:'—')].filter(Boolean).join('\n\n')}
function button(label,fn){const b=document.createElement('button');b.type='button';b.className='quiet';b.textContent=label;b.disabled=busy;b.onclick=()=>{if(!busy)fn()};return b}
function link(label,url){const a=document.createElement('a');a.href=url;a.textContent=label;a.target='_blank';a.rel='noopener noreferrer';return a}
function render(){
 document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';picker.value=language;localizeLanguagePicker(picker,language);document.querySelector('[data-ui=language]').textContent=t()[0];document.querySelectorAll('[data-p]').forEach(el=>el.textContent=t()[Number(el.dataset.p)]);$('headline').textContent=details()[0];$('subtitle').textContent=details()[1];$('photo-note').textContent=t()[wardrobe?50:56];
 CATEGORIES[domain].forEach((value,i)=>$('category').querySelector('[value="'+value+'"]').textContent=details()[2][i]);CONDITIONS.forEach((value,i)=>$('condition').querySelector('[value="'+value+'"]').textContent=t()[10+i]);PLANS.forEach((value,i)=>$('plan').querySelector('[value="'+value+'"]').textContent=t()[16+i]);
 const filter=$('filter').value,locations=[...new Set(records.map(r=>r.location).filter(Boolean))].sort();$('filter').replaceChildren();const all=document.createElement('option');all.value='';all.textContent=t()[30];$('filter').append(all);for(const value of locations){const option=document.createElement('option');option.value=value;option.textContent=value;$('filter').append(option)}$('filter').value=locations.includes(filter)?filter:'';
 $('summary').textContent=records.length+' '+t()[28]+' · '+records.filter(needsReview).length+' '+t()[29];$('undo').hidden=!removed;$('inventory').replaceChildren();const shown=records.filter(r=>!$('filter').value||r.location===$('filter').value);if(!shown.length)$('inventory').textContent=t()[43];
 for(const item of shown){const card=document.createElement('article');card.className='record';const heading=document.createElement('h3');heading.textContent=item.name;const meta=document.createElement('p');meta.textContent=[details()[2][CATEGORIES[domain].indexOf(item.category)],item.location,t()[16+PLANS.indexOf(item.plan)],needsReview(item)?t()[29]:'',wardrobe?item.wears+' · '+t()[22]:''].filter(Boolean).join(' · ');card.append(heading,meta);const actions=document.createElement('div');actions.className='toolbar';
 actions.append(button(t()[31],()=>{resetPhoto();editing=item.id;for(const field of fields)$(field).value=item[field]??'';$('checked').checked=item.checked;$('attach').checked=false;$('name').focus();$('editor').scrollIntoView({behavior:'smooth',block:'start'})}),button(t()[35],()=>{$('draft').value=saleDraft(item);$('draft').hidden=false;$('draft').focus();$('draft').scrollIntoView({behavior:'smooth',block:'center'})}));
 if(wardrobe){actions.append(button(t()[54],()=>save(records.map(r=>r.id===item.id?{...r,wears:Math.min(100000,r.wears+1)}:r))));const search=new URL('https://www.ebay.com/sch/i.html');search.searchParams.set('_nkw',[item.brand,item.model,item.name,item.size].filter(Boolean).join(' '));search.searchParams.set('LH_Sold','1');search.searchParams.set('LH_Complete','1');actions.append(link(t()[52],search.href));}
 else{const target=specialistFor(item);if(target)actions.append(button(t()[34]+' · '+target.toUpperCase(),()=>{try{window.location.href=prepareHandoff(sessionStorage,target,itemDescription(item))}catch{notify(42)}}));}
 if(item.report)actions.append(button(t()[58],()=>download(item.report,domain+'-'+item.id+'-report.txt','text/plain;charset=utf-8')));
 actions.append(button(t()[32],()=>{removed={item,index:records.findIndex(r=>r.id===item.id)};save(records.filter(r=>r.id!==item.id))}));card.append(actions);$('inventory').append(card)}
 const guide=specialistGuide(domain,language);$('specialist-guide').replaceChildren();const h=document.createElement('h2');h.textContent=guide.labels[0];$('specialist-guide').append(h);const list=document.createElement('ul');for(const question of guide.questions){const li=document.createElement('li');li.textContent=question;list.append(li)}$('specialist-guide').append(list);for(const [title,url]of guide.sources)$('specialist-guide').append(link(title+' ↗',url));
}
$('item-form').onsubmit=event=>{event.preventDefault();if(busy)return;try{const item=current();if(!editing&&records.length>=1000)throw Error('limit');save(editing?records.map(r=>r.id===editing?item:r):[...records,item]);reset()}catch{notify(42)}};
$('new').onclick=()=>{if(!busy)reset()};$('filter').onchange=render;
$('undo').onclick=()=>{if(!removed||records.length>=1000)return;const next=[...records];next.splice(removed.index,0,removed.item);removed=null;save(next)};
$('csv').onclick=()=>download(inventoryCSV(records),domain+'-inventory.csv','text/csv;charset=utf-8');$('backup').onclick=()=>download(JSON.stringify({version:1,domain,records},null,2),domain+'-backup.json','application/json');
$('restore').onchange=async()=>{if(busy)return;const file=$('restore').files[0];if(!file)return;try{if(file.size>64*1024*1024)throw Error('size');save(mergeInventory(records,JSON.parse(await file.text()),domain))}catch{notify(42)}finally{$('restore').value=''}};
picker.onchange=()=>{if(busy||!UI[picker.value])return;language=picker.value;try{localStorage.setItem(key+'-language',language)}catch{}$('notice').textContent='';render()};
$('photo').onchange=async()=>{resetPhotoAfterSelection();const version=selection,file=$('photo').files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){notify(42);return;}photoURL=URL.createObjectURL(file);const img=new Image();img.src=photoURL;img.alt=file.name;$('preview').append(img);if(!wardrobe)return;try{await img.decode();if(version!==selection)return;const scale=Math.min(1,1600/img.naturalWidth,1600/img.naturalHeight),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const prepared=canvas.toDataURL('image/jpeg',0.85);if(prepared.length>4*1024*1024)throw Error('size');image=prepared;$('analyze').disabled=false;notify(59)}catch{if(version===selection)notify(49)}};
function resetPhotoAfterSelection(){selection++;image=null;report='';$('report').replaceChildren();$('preview').replaceChildren();$('analyze').disabled=true;if(photoURL)URL.revokeObjectURL(photoURL);photoURL=null}
$('analyze').onclick=async()=>{if(!wardrobe||!image||busy)return;let item;try{item=current()}catch{notify(42);return}busy=true;picker.disabled=true;for(const control of $('editor').querySelectorAll('input,select,textarea,button'))control.disabled=true;$('photo').disabled=true;$('analyze').disabled=true;notify(48);
 try{const response=await fetch('/api/wardrobevue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,description:itemDescription(item),language,action:'value',market:'Sweden',currency:item.currency}),signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('api');const data=await response.json();if(typeof data.analysis!=='string'||!data.analysis.trim())throw Error('report');report=data.analysis;$('report').textContent=report;
 if(data.valuation){const v=data.valuation;const p=document.createElement('p');p.textContent=RANGE[language]+': '+[v.low,v.high].map(value=>new Intl.NumberFormat(language,{style:'currency',currency:v.currency}).format(value)).join(' – ')+' · '+v.count+' · '+v.basis;report+='\n\n'+p.textContent;$('report').append(p)}
 if(data.researchSources?.length){const heading=document.createElement('h4');heading.textContent=CONTEXT[language];$('report').append(heading);report+='\n'+CONTEXT[language]}
 for(const source of [...data.comparables||[],...data.researchSources||[]]){try{const url=new URL(source.url);if(url.protocol!=='https:')continue;const p=document.createElement('p');p.append(link(source.title||url.hostname,url.href));$('report').append(p);report+='\n'+(source.title||url.hostname)+' '+url.href}catch{}}
 $('notice').textContent='';
 }catch{notify(49)}finally{busy=false;picker.disabled=false;for(const control of $('editor').querySelectorAll('input,select,textarea,button'))control.disabled=false;$('photo').disabled=false;$('analyze').disabled=!image}};
window.addEventListener('pagehide',()=>{if(photoURL)URL.revokeObjectURL(photoURL)});render();if(loadError)notify(42);
try{const handed=consumeHandoff(sessionStorage,domain);if(handed!==null){$('name').value=handed.split('\n')[0].slice(0,180);$('notes').value=handed.slice(0,2000)}}catch{}
